"""Add flags and flagged_as_fake columns to Review

Revision ID: 1cc6b3e21ac1
Revises: 391aa4f2f5f3
Create Date: 2024-10-21 21:31:26.843822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cc6b3e21ac1'
down_revision = '391aa4f2f5f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flags', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('flagged_as_fake', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('flagged_as_fake')
        batch_op.drop_column('flags')

    # ### end Alembic commands ###
