"""Add sentiment column to Review model

Revision ID: 391aa4f2f5f3
Revises: 
Create Date: 2024-10-13 21:45:58.732285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '391aa4f2f5f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sentiment', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('sentiment')

    # ### end Alembic commands ###
